services:
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--maxmemory", "1024mb", "--maxmemory-policy", "allkeys-lru"]

  go-email:
    build: .
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

volumes:
  redis-data:
    